apiVersion: v1
kind: Namespace
metadata:
  name: bar
  labels:
    environment-id: env_d1279475-f80f-4dae-8ade-9924275fef72
    project-id: project_5079a412-f001-425f-9407-fc7b2737c054
    project-name: Port501
    environment-name: prod
    organization-id: org_01b50229-db34-43d4-8f3e-d1aeb683d900
